spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minnesladan
    username: minnesladan
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
